#!/bin/sh
set -e
package_name=timesyncd-fix
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/etc/systemd/timesyncd.conf"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/etc/systemd/timesyncd.conf"
;;
esac
exit 0
